/**
 * Menyusun hasil sesi latihan menjadi berkas yang bisa disimpan.
 *
 * # Kenapa CSV dan bukan XLSX
 *
 * XLSX adalah arsip ZIP berisi beberapa berkas XML, dan menyusunnya di
 * peramban menuntut pustaka berukuran ratusan kilobyte — beberapa kali lipat
 * seluruh situs ini, yang hanya 52 KB. CSV dibuka Excel, Google Sheets, dan
 * pandas tanpa satu bita pun tambahan.
 *
 * Tiga hal yang wajib benar agar berkasnya sungguh terbuka rapi di Excel:
 * BOM UTF-8 di depan (tanpa itu Excel di Windows membacanya sebagai ANSI),
 * baris `sep=,` paling atas (Excel berwilayah Indonesia memakai titik koma),
 * dan akhir baris CRLF seperti dituntut RFC 4180.
 *
 * # Kenapa isinya mengikuti bahasa yang sedang aktif
 *
 * Karena berkas ini dibaca oleh orang yang sama yang baru saja mengerjakan
 * sesinya. Rapor berbahasa Indonesia untuk sesi yang dikerjakan dalam bahasa
 * Inggris memaksa pembacanya menerjemahkan sendiri istilah yang barusan ia
 * baca dalam bahasa lain.
 *
 * .Deckyx
 */

import { namaTopik } from "./bank";
import type { Penilaian, Ringkasan, Soal } from "./bank";
import { bi, type Bilingual } from "./i18n";

const CR = String.fromCharCode(13);
const LF = String.fromCharCode(10);
const AKHIR_BARIS = CR + LF;
const BOM = "﻿";

export type Sel = string | number | null | undefined;

/** Satu sel CSV, dikutip bila perlu. */
export function sel(nilai: Sel): string {
  if (nilai === null || nilai === undefined) return "";
  const teks = typeof nilai === "number" ? String(nilai) : nilai;
  if (/[",\r\n]/.test(teks)) return `"${teks.replace(/"/g, '""')}"`;
  return teks;
}

/** Menyusun baris menjadi teks CSV yang siap diunduh. */
export function csv(baris: Sel[][]): string {
  const isi = [`${BOM}sep=,`];
  for (const b of baris) isi.push(b.map(sel).join(","));
  return isi.join(AKHIR_BARIS) + AKHIR_BARIS;
}

/** Label rapor dalam dua bahasa. */
export const LABEL = {
  judul: bi("Rapor sesi latihan IND323", "IND323 practice session report"),
  dihasilkan: bi("dihasilkan", "generated by"),
  ringkasan: bi("RINGKASAN", "SUMMARY"),
  nilai: bi("nilai", "score"),
  benar: bi("benar", "correct"),
  total: bi("total soal", "total questions"),
  waktu: bi("waktu terpakai (detik)", "time taken (seconds)"),
  benih: bi("benih sesi", "session seed"),
  bahasa: bi("bahasa rapor", "report language"),
  perTopik: bi("KETEPATAN PER TOPIK", "ACCURACY PER TOPIC"),
  topik: bi("topik", "topic"),
  bagian: bi("bagian benar", "share correct"),
  rincian: bi("RINCIAN TIAP SOAL", "PER-QUESTION DETAIL"),
  no: bi("no", "no"),
  kode: bi("kode", "code"),
  sesi: bi("sesi", "session"),
  pertanyaan: bi("pertanyaan", "question"),
  hasilnya: bi("hasil", "result"),
  pembahasan: bi("pembahasan", "explanation"),
  ya: bi("benar", "correct"),
  tidak: bi("salah", "wrong"),
  catatan: bi("CATATAN", "NOTES"),
  catatanBenih: bi(
    "Sesi dengan benih yang sama selalu berisi soal yang sama dalam urutan " +
      "yang sama. Pakai benih di atas untuk mengulang sesi ini persis.",
    "A session with the same seed always contains the same questions in the " +
      "same order. Use the seed above to repeat this session exactly.",
  ),
  catatanDesimal: bi(
    "Angka memakai titik sebagai pemisah desimal. Excel berwilayah Indonesia " +
      "mungkin membacanya sebagai teks.",
    "Numbers use a full stop as the decimal separator.",
  ),
} as const;

export interface Rapor {
  ringkasan: Ringkasan;
  soal: readonly Soal[];
  penilaian: readonly Penilaian[];
  detik: number;
  benih: string;
}

/**
 * Seluruh isi rapor sebagai baris CSV.
 *
 * `pilih` diserahkan pemanggilnya alih-alih diimpor langsung dari modul rune,
 * supaya berkas ini tetap bisa diimpor CPython-nya Vitest — modul rune hanya
 * bisa diurai perkakas Svelte, dan kode yang tidak bisa diimpor tidak bisa
 * diuji.
 */
export function barisRapor(rapor: Rapor, pilih: (p: Bilingual) => string): Sel[][] {
  const baris: Sel[][] = [];
  const L = LABEL;

  baris.push([pilih(L.judul)]);
  baris.push([pilih(L.dihasilkan), "xyb3rpunq.github.io/ind323-ai-lab (.Deckyx)"]);
  // Bahasanya dicatat supaya rapor yang beredar lepas dari halamannya tetap
  // bisa ditelusuri asalnya. Kodenya diambil dari `pilih` itu sendiri: ia
  // memang fungsi yang memilih salah satu dari sepasang, jadi memberinya
  // pasangan berisi kedua kode bahasa mengembalikan yang sedang aktif.
  baris.push([pilih(L.bahasa), pilih(bi("id", "en"))]);
  baris.push([]);

  baris.push([pilih(L.ringkasan)]);
  baris.push([pilih(L.nilai), Math.round(rapor.ringkasan.nilai)]);
  baris.push([pilih(L.benar), rapor.ringkasan.benar]);
  baris.push([pilih(L.total), rapor.ringkasan.total]);
  baris.push([pilih(L.waktu), rapor.detik]);
  baris.push([pilih(L.benih), rapor.benih]);
  baris.push([]);

  baris.push([pilih(L.perTopik)]);
  baris.push([pilih(L.topik), pilih(L.benar), pilih(L.total), pilih(L.bagian)]);
  for (const t of rapor.ringkasan.perTopik) {
    baris.push([
      pilih(namaTopik(t.topik)),
      t.benar,
      t.total,
      t.total > 0 ? t.benar / t.total : 0,
    ]);
  }
  baris.push([]);

  baris.push([pilih(L.rincian)]);
  baris.push([
    pilih(L.no),
    pilih(L.kode),
    pilih(L.sesi),
    pilih(L.topik),
    pilih(L.pertanyaan),
    pilih(L.hasilnya),
    pilih(L.pembahasan),
  ]);
  rapor.soal.forEach((s, i) => {
    // Penilaian dicocokkan lewat kodenya, bukan lewat urutannya. Sebuah sesi
    // yang ditinggalkan di tengah menghasilkan penilaian yang lebih pendek
    // daripada soalnya, dan mencocokkan berdasar indeks akan menggeser seluruh
    // baris sesudahnya tanpa satu pun galat.
    const p = rapor.penilaian.find((x) => x.kode === s.kode);
    baris.push([
      i + 1,
      s.kode,
      s.sesi,
      pilih(namaTopik(s.topik)),
      pilih(s.pertanyaan),
      p === undefined ? "" : pilih(p.benar ? L.ya : L.tidak),
      pilih(s.pembahasan),
    ]);
  });
  baris.push([]);

  baris.push([pilih(L.catatan)]);
  baris.push([pilih(L.catatanBenih)]);
  baris.push([pilih(L.catatanDesimal)]);
  return baris;
}

/** Nama berkas yang menyebutkan benih dan nilainya, bukan sekadar tanggal. */
export function namaBerkas(rapor: Rapor, akhiran = "csv"): string {
  const kini = new Date();
  const dua = (n: number) => String(n).padStart(2, "0");
  const cap = `${kini.getFullYear()}${dua(kini.getMonth() + 1)}${dua(kini.getDate())}`;
  // Benih berasal dari isian pengguna dan bisa memuat apa saja. Dibersihkan
  // sebelum masuk ke nama berkas: titik dua dan garis miring membuat unduhan
  // gagal senyap di Windows.
  const benih = rapor.benih.replace(/[^0-9A-Za-z-]/g, "").slice(0, 20) || "0";
  const nilai = Math.round(rapor.ringkasan.nilai);
  return `ind323-rapor-${cap}-benih${benih}-nilai${nilai}.${akhiran}`;
}

/** Menyerahkan sebuah berkas kepada pengguna. */
export function unduh(nama: string, teks: string, jenis: string): void {
  const gumpal = new Blob([teks], { type: jenis });
  const alamat = URL.createObjectURL(gumpal);
  const tautan = document.createElement("a");
  tautan.href = alamat;
  tautan.download = nama;
  document.body.append(tautan);
  tautan.click();
  tautan.remove();
  // Yang tidak dilepas menahan seluruh isi berkasnya di memori sampai tabnya
  // ditutup.
  URL.revokeObjectURL(alamat);
}

/** Menyusun rapor menjadi CSV lalu mengunduhnya. */
export function unduhRapor(rapor: Rapor, pilih: (p: Bilingual) => string): string {
  const nama = namaBerkas(rapor);
  unduh(nama, csv(barisRapor(rapor, pilih)), "text/csv;charset=utf-8");
  return nama;
}
